### PR TITLE
use multiple tabs

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
@westy92 this aims to be a port of @rhyek's parallel tab changes from https://github.com/westy92/html-pdf-chrome/pull/24

**Comment by graingert** [comment]
```js
const chrome = await htmlPdf.init(chromeOptions);

...
await htmlPdf.create(chrome, html, options);
```

**Comment by graingert** [comment]
@westy92 this PR is ready to go, I've created a subset of this PR [here](https://github.com/westy92/html-pdf-chrome/pull/63) because I cannot get the tests to pass reliably (even on master)

**Comment by miguelduarte42** [comment]
Any idea when this PR will be finalised?

**Comment by westy92** [comment]
@graingert can you sync up with master and we can work to get this merged?  Thanks!

**Comment by graingert** [comment]
@westy92 sorry, I've not got time to work on this PR (I'm using puppeteer now)

**Comment by westy92** [comment]
This inspired changes that landed in https://github.com/westy92/html-pdf-chrome/commit/89f63ad391e54d7bb734df8c8b694c0571f8b651 and will be released with v0.5.0.

**Pull request closed without merging**
